var fs = require('fs');
var path = require('path');
var Webtorrent = require('webtorrent');
var magnet = require('magnet-uri')

var client = new Webtorrent();
var comment = "Webtorrent DEV 3 no magnets"
var filePath = 'files/test/'+comment+'.txt'
var date = new Date(Date.now());
var timeStamp = ('0' + date.getDate()).slice(-2) + '/' + ('0' + (date.getMonth() + 1)).slice(-2) + '/' + date.getFullYear() + ' ' + ('0' + date.getHours()).slice(-2) + ':' + ('0' + date.getMinutes()).slice(-2);

fs.appendFile(filePath, '\n Generated by webtorrent at ['+timeStamp+']\n', function(err) {
    if(err) {
        return console.log(err);
    }  
});

var fileName = path.basename(filePath,'.txt');
var magnet_file_name = "webtorrent_magnet_for_("+fileName+').txt';
var magnetLogFile = 'files/magnets/'+magnet_file_name;

client.seed(filePath, function (torrent) {
	magnetURI = torrent.magnetURI;
	parsed = magnet(magnetURI);
	content = magnetURI+'\n'+parsed+'\n'
	fs.appendFile(magnetLogFile,content, function(err) {
	    if(err) {
	        return console.log(err);
	    }
	    console.log("["+content+"] Saved to magnets file ["+magnet_file_name+']');
	});
});